usr/libexec/tracker-extract-3
usr/libexec/tracker-writeback-3

usr/libexec/tracker3/daemon
usr/libexec/tracker3/extract
usr/libexec/tracker3/index
usr/libexec/tracker3/info
usr/libexec/tracker3/reset
usr/libexec/tracker3/search
usr/libexec/tracker3/status
usr/libexec/tracker3/tag

usr/lib/*/tracker-miners-3.0/libtracker-extract.so
usr/lib/*/tracker-miners-3.0/extract-modules/*.so

usr/lib/systemd/user/tracker-extract-3.service
usr/lib/systemd/user/tracker-writeback-3.service

usr/share/dbus-1/interfaces/org.freedesktop.Tracker3.Miner.xml

usr/share/dbus-1/services/org.freedesktop.Tracker3.Miner.Extract.service
usr/share/dbus-1/services/org.freedesktop.Tracker3.Writeback.service

usr/share/man/man1/tracker3-extract.1*

usr/share/tracker3-miners/extract-rules/
usr/share/tracker3-miners/domain-ontologies/

usr/lib/*/tracker-miners-3.0/writeback-modules/*.so

usr/share/man/man1/tracker3-tag.1*
usr/share/man/man1/tracker3-status.1*
usr/share/man/man1/tracker3-search.1*
usr/share/man/man1/tracker3-reset.1*
usr/share/man/man1/tracker3-info.1*
usr/share/man/man1/tracker3-index.1*
usr/share/man/man1/tracker3-extract.1*
usr/share/man/man1/tracker3-daemon.1*
usr/share/man/man1/tracker-writeback-3.1*

usr/share/glib-2.0/schemas/org.freedesktop.Tracker3.Extract.gschema.xml
usr/share/glib-2.0/schemas/org.freedesktop.Tracker3.FTS.gschema.xml
usr/share/glib-2.0/schemas/org.freedesktop.Tracker3.Miner.Files.gschema.xml
usr/share/glib-2.0/schemas/org.freedesktop.TrackerMiners3.enums.xml

usr/share/locale
